### ISSUE TITLE
Service proxy generation uses deprecated API

### ISSUE THREAD

**Issue by aygalinc** [vert-x3/vertx-service-proxy#104]
Hi,

I notice during some of my build that service proxy generation relies on vert.x deprecated API. 

Here is som mvn log : 
```
ING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxProxyHandler.java:[38,29] io.vertx.serviceproxy.ProxyHelper in io.vertx.serviceproxy has been deprecated
[WARNING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxEBProxy.java:[31,29] io.vertx.serviceproxy.ProxyHelper in io.vertx.serviceproxy has been deprecated
[WARNING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxProxyHandler.java:[38,29] io.vertx.serviceproxy.ProxyHelper in io.vertx.serviceproxy has been deprecated
[WARNING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxEBProxy.java:[31,29] io.vertx.serviceproxy.ProxyHelper in io.vertx.serviceproxy has been deprecated
[WARNING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxProxyHandler.java:[38,29] io.vertx.serviceproxy.ProxyHelper in io.vertx.serviceproxy has been deprecated
[WARNING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxEBProxy.java:[31,29] io.vertx.serviceproxy.ProxyHelper in io.vertx.serviceproxy has been deprecated
[WARNING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxEBProxy.java:[87,22] <T>send(java.lang.String,java.lang.Object,io.vertx.core.eventbus.DeliveryOptions,io.vertx.core.Handler<io.vertx.core.AsyncResult<io.vertx.core.eventbus.Message<T>>>) in io.vertx.core.eventbus.EventBus has been deprecated
[WARNING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxEBProxy.java:[106,22] <T>send(java.lang.String,java.lang.Object,io.vertx.core.eventbus.DeliveryOptions,io.vertx.core.Handler<io.vertx.core.AsyncResult<io.vertx.core.eventbus.Message<T>>>) in io.vertx.core.eventbus.EventBus has been deprecated
[WARNING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxEBProxy.java:[125,22] <T>send(java.lang.String,java.lang.Object,io.vertx.core.eventbus.DeliveryOptions,io.vertx.core.Handler<io.vertx.core.AsyncResult<io.vertx.core.eventbus.Message<T>>>) in io.vertx.core.eventbus.EventBus has been deprecated
[WARNING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxEBProxy.java:[144,22] <T>send(java.lang.String,java.lang.Object,io.vertx.core.eventbus.DeliveryOptions,io.vertx.core.Handler<io.vertx.core.AsyncResult<io.vertx.core.eventbus.Message<T>>>) in io.vertx.core.eventbus.EventBus has been deprecated
[WARNING] /home/caygalin/Workspace/forum-head/gxl.forum.services/target/generated-sources/annotations/com/se/gxl/forum/service/ForumServiceVertxEBProxy.java:[163,22] <T>send(java.lang.String,java.lang.Object,io.vertx.core.eventbus.DeliveryOptions,io.vertx.core.Handler<io.vertx.core.AsyncResult<io.vertx.core.eventbus.Message<T>>>) in io.vertx.core.eventbus.EventBus has been deprecated
```

**Comment by castx1981** [comment]
In *VertxEBProxy, the code is using
`  <T> EventBus send(String address, Object message, DeliveryOptions options, Handler<AsyncResult<Message<T>>> replyHandler);
`
which is marked as deprecated, it should use the request method instead.

@vietj

**Comment by vietj** [comment]
@castx1981 it should be fixed now in 3.8.1

**Comment by castx1981** [comment]
@vietj I checked the 3.8.1 [release](https://github.com/vert-x3/vertx-service-proxy/blob/31da8d6a076f5364d6241cb71850c98a49169526/src/main/java/io/vertx/serviceproxy/generator/ServiceProxyGen.java#L174), it is not fixed, the generated code is still using the deprecated **send** api. 

However it is fixed in the master branch.

**Comment by vietj** [comment]
oh right @castx1981 I was actually thinking of `ProxyHelper` class

**Comment by vietj** [comment]
@castx1981 it should be good now in 3.8 branch

**Comment by brunobastosg** [comment]
Is this suppposed to be fixed in 3.8.1 or in the next 3.8.x version? I just generated a proxy and it still used the deprecated `send` method.

**Comment by vietj** [comment]
it will be in 3.8.2 , you can check yourself with the current 3.8.2-SNAPSHOT published in Sonatype's OSS repo
